### PR TITLE
make for ts

### PR DESCRIPTION
**Pull request by jread-usgs**
@aappling-usgs can you take a look?

### CODE REVIEW

**Comment by aappling-usgs** [comment]
do `time.st` and `time.en` ever get modified?

**Comment by aappling-usgs** [comment]
i assume that if you run remake multiple times, it keeps updating until everything is as complete as it can be and then it stops doing anything when you call remake after that. right? but i don't fully understand how that works - would appreciate an explanation either here or maybe when we talk tomorrow. what files or properties of files signal that everything is done?

**Comment by jread-usgs** [comment]
That is correct and we can go over it. 

What signals "done" is the file having `remote=TRUE` or `no.data=TRUE`, so once a table has all files with one of those two cases met, it will be skipped over.

**Comment by jread-usgs** [comment]
time.en and time.st are modified in the timeseries yaml, which is currently poorly named as `nldas_ts.yaml` I think. But that is where you would change the times

**Comment by aappling-usgs** [comment]
ok, thanks. i found `nldas_ts.yaml` but had been thinking that maybe after running everything, the file would then have time ranges that are different in each row to reflect the actual extent of each dataset? or are they always identical within each column?

stopping once the table has all `remote==TRUE | no.data==TRUE` sounds perfect & awesome.

**Pull request merged**
