### PR TITLE
remake revisions, splitting source code files by function

### PR DESCRIPTION
**Pull request by aappling-usgs**
@jread-usgs could you look at remake/1_ldas_host.yml especially and maybe even try it on your system?

### CODE REVIEW

**Comment by jread-usgs** [comment]
here is what I get when running your fork's remake on `ldas`:
```
remake::make(remake_file='1_ldas_host.yml')
[  LOAD ] 
[  READ ]                                        |  # loading sources
<  MAKE > 1_ldas_host
[ BUILD ] internal.config                        |  internal.config <- load_profile()
[  READ ]                                        |  # loading packages
[ BUILD ] nldas.config                           |  nldas.config <- yaml.load_file("../1_ldas_host/in/nldas_subset.yaml")
[ BUILD ] gldas.config                           |  gldas.config <- yaml.load_file("../1_ldas_host/in/gldas_subset.yaml")
[ BUILD ] nldas.grids                            |  nldas.grids <- nc_sub_grids(nldas.config, "nldas.grids")
[ BUILD ] gldas.grids                            |  gldas.grids <- nc_sub_grids(gldas.config, "gldas.grids")
[ BUILD ] ../1_ldas_host/out/nldas_nc_files.tsv  |  ldas_sub_files(nldas.grids, nldas.config, "../1_ldas_host/out/nldas_nc_files.tsv")
[ BUILD ] ../1_ldas_host/out/nldas_nc_status.txt |  nccopy_ldas("../1_ldas_host/out/nldas_nc_files.tsv", "../1_ldas_host/out/nldas_nc_status.txt", internal.config)
no new files to nccopy, doing nothing
[ BUILD ] ../1_ldas_host/out/gldas_nc_files.tsv  |  ldas_sub_files(gldas.grids, gldas.config, "../1_ldas_host/out/gldas_nc_files.tsv")
[ BUILD ] ../1_ldas_host/out/gldas_nc_status.txt |  nccopy_ldas("../1_ldas_host/out/gldas_nc_files.tsv", "../1_ldas_host/out/gldas_nc_status.txt", internal.config)
no new files to nccopy, doing nothing
[ BUILD ] nldas.server.files                     |  nldas.server.files <- ldas_server_files(nldas.config)
[ BUILD ] gldas.server.files                     |  gldas.server.files <- ldas_server_files(gldas.config)
[ BUILD ] ../1_ldas_host/out/nldas.ncml          |  create_ldas_ncml(nldas.server.files, "../1_ldas_host/out/nldas.ncml")
[ BUILD ] ../1_ldas_host/out/gldas.ncml          |  create_ldas_ncml(gldas.server.files, "../1_ldas_host/out/gldas.ncml", gldas.config)
[ BUILD ] nldas.ncml.sync                        |  nldas.ncml.sync <- sync_ncml("../1_ldas_host/out/nldas.ncml", internal.config)
[ BUILD ] gldas.ncml.sync                        |  gldas.ncml.sync <- sync_ncml("../1_ldas_host/out/gldas.ncml", internal.config)
```

**Comment by jread-usgs** [comment]
and then updating the end time of the nldas subset, I get the expected:

```
remake::make(remake_file='1_ldas_host.yml')
<  MAKE > 1_ldas_host
[    OK ] internal.config
[ BUILD ] nldas.config                           |  nldas.config <- yaml.load_file("../1_ldas_host/in/nldas_subset.yaml")
[    OK ] gldas.config
[ BUILD ] nldas.grids                            |  nldas.grids <- nc_sub_grids(nldas.config, "nldas.grids")
[    OK ] gldas.grids
[ BUILD ] ../1_ldas_host/out/nldas_nc_files.tsv  |  ldas_sub_files(nldas.grids, nldas.config, "../1_ldas_host/out/nldas_nc_files.tsv")
remove: NLDAS_325675.326387_0.223_0.463_pressfc.nc NLDAS_325675.326387_0.223_0.463_dswrfsfc.nc
Restoring previous version of ../1_ldas_host/out/nldas_nc_files.tsv
 Show Traceback
 
 Rerun with Debug
 Error in ldas_sub_files(nldas.grids, nldas.config, "../1_ldas_host/out/nldas_nc_files.tsv") : 
  
2 files are on the server but are no longer used and can be removed... 
```
which is good

**Comment by aappling-usgs** [comment]
nice! so that remakefile works entirely as we'd like?

**Comment by jread-usgs** [comment]
👍

**Pull request merged**
