### PR TITLE
get build started on Winslow Tower

### PR DESCRIPTION
**Pull request by aappling-usgs**
@jread-usgs - I've pulled updates for mda.streams, streamMetabolizer, and stream_metab_usa onto Luke's old tower so I can pull in the last few tses there. When I ran `remake` for `sb_dosat_calcGGbconst`, `remake` decided it needed up update the site_list.tsv, too. This PR has the changes. 

I'm not surprised that the `indy` or `styx` sites disappeared, because they shouldn't be part of the data pub and so I made them invisible to cidamanager. 

But I am surprised how many other changes there were. A few new sites, some changes from no.data=TRUE to no.data=FALSE, and some changes from no.data=FALSE to no.data=TRUE. Is that consistent with what you know about this winter's data pull status? Do you think maybe you just didn't post a recent update to site_list.tsv, or have all these changes occurred in the last two weeks?

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Can now confirm that all those ts tables were out of date because they were missing 17 sites. Redoing.

**Comment by jread-usgs** [comment]
@aappling-usgs is the question above about the no.data moot because of the tables being out of date? ☝️

**Comment by aappling-usgs** [comment]
Partially, but I'm still wondering whether your computer has un-committed site list and/or status tables. It does look like they're out of date, one way or another, but I'd like to know whether they're out of date because things have changed rapidly on NWIS this month or because things weren't up to date 2 weeks ago, either.

I found that calling remake with existing ts tables didn't do it - I've had to delete the tables entirely to get them to be up to date with the site list. Did you delete those tables two weeks ago or work with the previous ones?

Also therefore wondering whether we need to update the remake files, or maybe the documentation around them, so this is clearer next time around. The remake has dependencies like this:
```
  ../1_timeseries/out/files_ts_baro_nldas.tsv:
    command: create_ts_table(sb_sites, ts.config, target_name)
```
which I thought would cause the ts files to be recreated whenever sb_sites changes. And yet I'm not sure they were, because I was able to run calls like
```r
remake_smu('sb_dosat_calcGGbconst')
```
and see it run without updating, even though the site list was longer than the nrow of that ts status table. Shouldn't it have updated?

**Comment by jread-usgs** [comment]
Yes, I also had to delete the tables to get things to run properly. I am confused by what is going on and we should probably just talk over the phone about it.

**Comment by aappling-usgs** [comment]
After phone: oh, right! You intentionally had remake not build a new site list. That's why these are all different.

**Comment by aappling-usgs** [comment]
Conclusion: remake is fine, and our setup for remake is fine, and we're pulling down a little more data than is strictly necessary. That's OK; I'll just build my config for the model run using the list of sites I sent to Jud for coefficients.

On a second look, I think i see that `no.data` in the site status table indicates that one or more of these conditions is met:
1. the site no longer exists on NWIS
2. there are currently no `doobs` data, or fewer than 100 observations, available for that site
3. the site does not have one of the NWIS site types that we currently recognize (since last time, we've narrowed this list to just ['ST','ST-CA','ST-DCH','ST-TS','SP'])
So there are several legitimate reasons that we might get more `no.data` values this time around - I think (3) above probably explains most of them and may even confirm that sometime if I get a chance.

**Pull request merged**
