### PR TITLE
re-usable metadata templater 

### PR DESCRIPTION
**Pull request by jread-usgs**
@aappling-usgs this is a WIP (only part way through the required metadata) but the intent is to create a template that can be filled in by `whisker` and result in the complete xml. 

The result creates this:

```XML
<?xml version="1.0"?>
<metadata>
  <idinfo>
    <citation>
      <citeinfo>
        <origin>{{authors}}</origin>
        <pubdate>{{pubdate}}</pubdate>
        <title>{{title}}</title>
        <geoform>text files</geoform>
        <onlink>{{doi}}</onlink>
      </citeinfo>
    </citation>
    <descript>
      <abstract>{{abstract}}</abstract>
      <purpose>{{purpose}}</purpose>
    </descript>
    <timeperd>
      <timeinfo>
        <rngdates>
          <begdate>{{start-date}}</begdate>
          <enddate>{{end-date}}</enddate>
        </rngdates>
      </timeinfo>
    </timeperd>
    <status>
      <progress>Complete</progress>
      <update>{{update}}</update>
    </status>
    <spdom>
      <bounding>
        <westbc>{{wbbox}}</westbc>
        <eastbc>{{ebbox}}</eastbc>
        <northbc>{{nbbox}}</northbc>
        <southbc>{{sbbox}}</southbc>
      </bounding>
    </spdom>
    <keywords>
      <theme>
<themekt>none</themekt>
{{#themekeywords}}<themekey>{{.}}</themekey>
{{/themekeywords}}</theme>
      <theme>
        <themekt>ISO 19115 Topic Category</themekt>
        <themekey>environment</themekey>
        <themekey>inlandWaters</themekey>
        <themekey>007</themekey>
        <themekey>012</themekey>
      </theme>
    </keywords>
    <place>
      <placekt>Department of Commerce, 1995, Countries, Dependencies, Areas of Special Sovereignty, and 
                Their Principal Administrative Divisions,  Federal Information Processing Standard (FIPS) 10-4, 
                Washington, D.C., National Institute of Standards and Technology</placekt>
      <placekey>United States</placekey>
      <placekey>US</placekey>
    </place>
    <place>
{{#states}}<placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, 
                the District of Columbia and the outlying areas of the United States, and associated areas 
                (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>
                <placekey>{{.}}</placekey>
{{/states}}</place>
  </idinfo>
</metadata>
```

and the `#states` and `#themekeywords` is supposed to loop through the state and themekeyword vectors to create multiple sections for those. a la:

```r
states <- c('WI','NH','NC')
template = '<place>
{{#states}}<placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, 
     the District of Columbia and the outlying areas of the United States, and associated areas 
    (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>
       <placekey>{{.}}</placekey>
        {{/states}}</place>'
whisker.render(template)
```
```XML
<place>
   <placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, \n    the District of Columbia and the outlying areas of the United States, and associated areas \n    (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>
   <placekey>WI</placekey>
   <placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, \n    the District of Columbia and the outlying areas of the United States, and associated areas \n    (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>\n        <placekey>NH</placekey>\n        <placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, \n    the District of Columbia and the outlying areas of the United States, and associated areas \n    (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>\n        <placekey>NC</placekey>\n        </place>
```
☝️ oh, I guess that isn't quite working right, but you get the point

### CODE REVIEW

**Comment by aappling-usgs** [comment]
cool. when you say "WIP", i never know whether i should merge right away or wait until someday down the line when you've decided the WIP is ready to merge. guidance?

**Comment by jread-usgs** [comment]
WIP to me means I want you to look at it so I am not going down a nasty path, and then merge when it is complete and reviewed

**Comment by jread-usgs** [comment]
what's a better way to throw up a prototype for early review? I am fine w/ changing the way I do that

**Comment by aappling-usgs** [comment]
i don't have a problem with merging a WIP prototype right away as long as it doesn't break the system. i suppose if you thought it might break the system, we'd want to go to a branching workflow. but i doubt that's the case here, right?

if i can assume that whenever you make a PR, you're ready for it to be reviewed and merged, then we're good. WIP away! =)

**Comment by aappling-usgs** [comment]
i have reviewed. the whisker + xml2 templating combo is awesome!

**Comment by jread-usgs** [comment]
revised:
```XML
<place>
	<placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States,the District of Columbia and the outlying areas of the United States, and associated areas (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>
	<placekey>WI</placekey>
</place>
<place>
	<placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, the District of Columbia and the outlying areas of the United States, and associated areas (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>
	<placekey>NH</placekey>
</place>
<place>
	<placekt>U.S. Department of Commerce, 1987, Codes for the identification of the States, the District of Columbia and the outlying areas of the United States, and associated areas (Federal Information Processing Standard 5-2): Washington, D. C., NIST</placekt>
	<placekey>NC</placekey>
</place>
```

**Comment by aappling-usgs** [comment]
mmm, yes, those are better newlines

**Pull request merged**
