### PR TITLE
Timeseries metadata

### PR DESCRIPTION
**Pull request by aappling-usgs**
multi-entity metadata file

### CODE REVIEW

**Comment by jread-usgs** [comment]
This looks good to me. Is there a list of metadata tables we _don't_ have filled out yet?

**Comment by jread-usgs** [comment]
Yes, I can take that on. Should I revise #150 to capture this task? Or was that meant for something different?

**Comment by aappling-usgs** [comment]
Maybe not #150, which is about creating a table for inclusion in the manuscript.  So I guess make a new one?

**Comment by jread-usgs** [comment]
oh, ok. I misread that. I will create a new issue to capture it.

**Pull request merged**
