### PR TITLE
remake update; yaml->yml

### PR DESCRIPTION
**Pull request by jread-usgs**
@aappling-usgs quick look?

### CODE REVIEW

**Comment by jread-usgs** [comment]
oh, I should get my file names in line w/ `1_timeseries`

**Comment by aappling-usgs** [comment]
:+1:

**Comment by jread-usgs** [comment]
or `4_data_release` if I am reading the table correctly.

**Comment by aappling-usgs** [comment]
oh, true.

also, could you please add this as line 1 in remake/4_data_release.yml?:
```yaml
target_default: 4_data_release
```

and then of course update the first target to be `4_data_release`, too.

example of this strategy in use: https://github.com/aappling-usgs/stream_metab_usa/blob/master/remake/1_site_data.yml#L1

**Comment by jread-usgs** [comment]
I think I've got it @aappling-usgs

**Comment by aappling-usgs** [comment]
awesome

**Pull request merged**
